import { categories, deliveryEn, galleriesEn, partners, winesEn } from '~/content/home/shared'
import type { HomeContent } from '~/content/home/types'

export const homeEn: HomeContent = {
  key: 'home-en',
  locale: 'en',
  path: '/en',
  langLabel: 'English',
  navigation: {
    menu: 'Pizzas',
    wines: 'Wines',
    visit: 'Visit us',
  },
  hero: {
    title: 'Neapolitan pizza in Ixelles with Italian wines and a warm neighborhood feel',
    lead: 'Three things you really should not compromise on.',
    bullets: ['A memorable pizza.', 'A good glass of wine.', 'A place worth coming back to.'],
    pdfHref: '/doc/pizza-vino-en.pdf',
    pdfLabel: 'Download menu',
    callLabel: 'Call',
    heroImage: '/img/header-def.jpg',
  },
  heroHighlight: {
    locationLabel: 'Ixelles, Brussels',
    title: 'Neapolitan pizza and Italian wine',
    description: 'Pizza Vino brings together Italian tradition, long-fermented dough and a wine selection designed to work beautifully at the table.',
    doughLabel: 'Dough',
    doughValue: '48–72h maturation',
    serviceLabel: 'Service',
    serviceValue: 'Dine-in, takeaway, delivery',
  },
  labels: {
    craftsmanshipTitle: 'Made with love',
    craftsmanshipSubtitle: 'A light dough resting for up to 72 hours, baked fast at high heat for a fragrant, airy crust.',
    galleryTitle: 'Gallery',
    gallerySubtitle: 'A look inside Pizza Vino: pizzas, oven, team and dining room.',
    menuIntroTitle: 'Now it is time for the menu',
    redPizzasTitle: 'Red pizzas',
    redPizzasDescription: 'Built on a tomato base inspired by the Campanian tradition and balanced for brightness, sweetness and depth.',
    whitePizzasTitle: 'White pizzas',
    whitePizzasDescription: 'No tomato, just texture, dairy, cured meats and vegetables arranged to let each ingredient stand out.',
    specialsTitle: 'Most requested specials',
    winesTitle: 'Wine selection',
    winesDescription: 'A focused Italian list designed to pair with pizza rather than compete with it.',
    testimonialsTitle: 'Your feedback matters to us',
    testimonialsSubtitle: 'Reviews help new guests trust us before their first visit. Thank you for sharing yours.',
    deliveryTitle: 'Delivery and takeaway',
    visitTitle: 'Visit Pizza Vino',
    addressTitle: 'Address',
    phoneTitle: 'Phone',
  },
  supportLinks: [
    {
      name: 'Authentic wood-fired craftsmanship',
      description: 'Our Valoriani oven gives the crust its light char, fast oven spring and unmistakable Neapolitan character.',
      imageSrc: '/img/forno.jpeg',
    },
    {
      name: 'High-quality Italian ingredients',
      description: 'From tomatoes and flour to charcuterie and cheeses, every product is selected to keep the pizza flavorful yet digestible.',
      imageSrc: '/img/pizza-primo-piano3.webp',
    },
    {
      name: 'Michele’s signature approach',
      description: 'Years of hands-on experience in Italy and abroad shaped a style that is technical, generous and rooted in tradition.',
      imageSrc: '/img/michele-one.jpeg',
    },
  ],
  categories,
  galleries: galleriesEn,
  redPizzas: [
    { name: 'Margherita', description: 'Tomato, basil and mozzarella.', price: '11,00' },
    { name: 'Regina', description: 'Tomato, basil and buffalo mozzarella.', price: '15,00' },
    { name: 'Principessa', description: 'Tomato, basil and smoked scamorza cheese.', price: '13,00' },
    { name: 'Burrata', description: "Tomato, basil, burratina d'Andria and datterini tomatoes.", price: '18,00' },
    { name: 'Marinara', description: 'Tomato, garlic, oregano and basil.', price: '10,00' },
    { name: 'Rucola Reggiano', description: 'Tomato, mozzarella, rocket and Parmigiano Reggiano.', price: '14,00' },
    { name: 'Porchetta Funghi', description: "Tomato, basil, mozzarella, porchetta d'Ariccia and mushrooms.", price: '16,00' },
    { name: 'Quattro Stagioni', description: "Tomato, basil, mozzarella, porchetta d'Ariccia, mushrooms, black olives and baked artichokes.", price: '17,00' },
    { name: 'Napoli', description: 'Tomato, mozzarella, capers, Cetara anchovies and oregano.', price: '15,00' },
    { name: 'Siciliana', description: 'Tomato, basil, mozzarella, capers, Cetara anchovies, black olives and garlic.', price: '16,00' },
    { name: 'Diavola', description: 'Tomato, basil, mozzarella and nduja.', price: '15,50' },
    { name: 'Bresaola e tartufo', description: 'Tomato, mozzarella, rocket, bresaola, grana flakes and black truffle.', price: '20,00' },
  ],
  whitePizzas: [
    { name: 'Salsiccia Friarelli', description: 'Fior di latte, basil, sausage and friarielli.', price: '17,00' },
    { name: '4 Formaggi', description: 'Fior di latte, smoked scamorza, gorgonzola, parmesan and basil.', price: '16,00' },
    { name: 'Fresca', description: 'Fior di latte, yellow and red datterini tomatoes, rocket and parmesan.', price: '16,00' },
    { name: 'Patate & Tartufo', description: 'Fior di latte, basil, potatoes and black truffle.', price: '20,00' },
    { name: 'Mortadella', description: 'Fior di latte, rocket, mortadella, pecorino, sun-dried tomato pesto and pistachios.', price: '20,00' },
    { name: 'Genovese', description: 'Fior di latte, Genovese pesto, Piennolo tomatoes, ricotta and toasted pine nuts.', price: '20,00' },
  ],
  specials: [
    { name: 'Amatrice', description: 'Red piennolo tomato, Tropea red onion, crispy guanciale, black pepper and basil.', price: '20,00' },
    { name: 'Porchetta & tartufo', description: "Tomato, basil, fiordilatte, Ariccia porchetta, mascarpone and black truffle.", price: '20,00' },
    { name: 'Nostra', description: 'Tomato, Apulian burratina, culatello, black truffle and basil.', price: '20,00' },
    { name: 'Piccantissima', description: 'Tomato, fiordilatte, spicy salami, nduja, half burrata and chili threads.', price: '20,00' },
    { name: 'Burrata & pesto', description: 'Tomato, burrata, cherry tomatoes, homemade Genovese pesto, pine nuts and parmesan flakes.', price: '20,00' },
    { name: 'Parmigiana', description: 'Tomato, buffalo mozzarella, eggplant, datterini tomatoes, parmesan flakes and oregano.', price: '20,00' },
  ],
  wines: winesEn,
  testimonials: [
    {
      id: 1,
      rating: 5,
      quote: 'If you want an original Italian pizza and a proper coffee, this is the place. Friendly staff and a genuinely warm atmosphere.',
      attribution: 'Okan35 B.',
    },
    {
      id: 2,
      rating: 5,
      quote: 'Thin crust, fresh toppings and really kind people. We loved it and will definitely come back for another evening with pizza and wine.',
      attribution: 'Wim Dekkers',
    },
    {
      id: 3,
      rating: 5,
      quote: 'Traditional flavors, creative combinations and a very solid wine choice. A proper stop if you care about quality pizza.',
      attribution: 'Lorenzo Vinc',
    },
  ],
  delivery: deliveryEn,
  footer: {
    description: 'Use the links below to reach us on the map, order pizza, or follow Pizza Vino online.',
    deliveryTitle: 'Order online',
    socialTitle: 'Follow Pizza Vino',
    legalLine: 'Pizza Vino · Avenue des Saisons 15, 1050 Ixelles · VAT BE 0727796146',
  },
}
