import { categories, deliveryEn, galleriesEn, winesEn } from '~/content/home/shared'
import type { HomeContent } from '~/content/home/types'

export const homeEn: HomeContent = {
  key: 'home-en',
  locale: 'en',
  path: '/en',
  langLabel: 'English',
  navigation: {
    menu: 'Pizzas',
    wines: 'Wines',
    visit: 'Contact',
  },
  hero: {
    title: 'Per chi ama la pizza',
    lead: "Three things you can't absolutely say no:",
    bullets: ['A delicious pizza.', 'A good glass of wine.', '...'],
    pdfHref: '/doc/pizza-vino-en.pdf',
    pdfLabel: 'Download menù',
    callLabel: 'Call',
    heroImage: '/img/header-def.jpg',
  },
  heroHighlight: {
    locationLabel: 'Ixelles, Brussels',
    title: 'Neapolitan pizza and Italian wine',
    description: 'Pizza Vino brings together Italian tradition, long-fermented dough and a wine selection designed to work beautifully at the table.',
    doughLabel: 'Dough',
    doughValue: '48–72h maturation',
    serviceLabel: 'Service',
    serviceValue: 'Dine-in, takeaway, delivery',
  },
  labels: {
    craftsmanshipTitle: 'Made with love',
    craftsmanshipSubtitle: 'Made with love',
    craftsmanshipBody: 'A light dough that rests between 48 and 72 hours before being used, made with high quality ingredients, to obtain a pronounced but hollowed out cornice; cooking in a combined gas / wood rotary oven at 450 ° C allows to preserve the authentic flavors of tomato and fiordilatte mozzarella.',
    galleryTitle: 'Gallery',
    gallerySubtitle: 'Gallery',
    menuIntroTitle: "But now it's time for ...",
    redPizzasTitle: 'Pizze Rosse',
    redPizzasDescription: 'Sauce made with Piennolo tomato, typical of the Vesuvian area of Campania, it owes its name to the way in which the tomato clusters are intertwined to be preserved. They have an oval but elongated shape and a typically sour taste.',
    whitePizzasTitle: 'Pizze bianche',
    whitePizzasDescription: 'Expressly designed without tomato sauce to enhance the typical flavors of unique Italian products. An amazing combination that will tickle your taste buds.',
    specialsTitle: 'Our most requested specials',
    winesTitle: 'Selection of wines',
    winesDescription: 'What matters is that this time there will be a good wine.',
    testimonialsTitle: 'To give importance to our customers',
    testimonialsSubtitle: 'we ask you to leave a comment. Because your comments are our best advertisement. Thanks!.',
    testimonialsListTitle: 'What are people saying?',
    deliveryTitle: 'Delivery and takeaway',
    visitTitle: 'Visit Pizza Vino',
    addressTitle: 'Address',
    phoneTitle: 'Phone',
  },
  supportLinks: [
    {
      name: 'Wood-fired oven',
      description: 'Absolutely Italian design for more than a century, excellent performance, Valoriani ovens are internationally recognized. Certifications and certificates received from the Neapolitan True Pizza Association, from partners such as Slow Food, Gambero Rosso, Witaly etc...',
      imageSrc: '/img/forno.jpeg',
    },
    {
      name: 'Quality products',
      description: 'For us it is important to serve a high quality pizza. High quality products at affordable prices to give customers a final product that is excellent to taste and easy to digest. The ingredients only Made in Italy (and the way they are processed) are, especially with regards to pizza, the most important part.',
      imageSrc: '/img/pizza-primo-piano3.webp',
    },
    {
      name: 'Il Pizzaiolo',
      description: 'Passionate about cooking since the age of 14, Michele decides during high school to start working in a restaurant-pizzeria in the province of Verona, where his roots lie. He arrives in Brussels at the age of 21 after a year of experience in Germany. In 2019 at the age of 27, he crowns the dream of opening his own restaurant where he is finally free to express his best concept of pizza.',
      imageSrc: '/img/michele-one.jpeg',
    },
  ],
  categories,
  galleries: galleriesEn,
  redPizzas: [
    { name: 'Margherita', description: 'Tomato, Basil and Mozzarella.', price: '11,00' },
    { name: 'Regina', description: 'Tomato, Basil and Mozzarella di Bufala.', price: '15,00' },
    { name: 'Principessa', description: 'Tomato, Basil and Smoked Scamorza Cheese.', price: '13,00' },
    { name: 'Burrata', description: "Tomato, Basil, Burratina d'Andria and Red Datterini Tomatoes.", price: '18,00' },
    { name: 'Marinara', description: 'Tomato, Garlic, Oregano and Basil.', price: '10,00' },
    { name: 'Rucola Reggiano', description: 'Tomato, Mozzarella, Rocket and Parmigiano Reggiano Cheese.', price: '14,00' },
    { name: 'Porchetta Funghi', description: "Tomato, Basil, Mozzarella, Porchetta d'Ariccia and Mushrooms.", price: '16,00' },
    { name: 'Quattro Stagioni', description: "Tomato, Basil, Mozzarella, Porchetta d'Ariccia, Mushrooms, Black Olives and Baked Artichokes.", price: '17,00' },
    { name: 'Napoli', description: 'Tomato, Mozzarella, Capers, Cetara Anchovy Fillets and Oregano.', price: '15,00' },
    { name: 'Siciliana', description: 'Tomato, Basil, Mozzarella, Capers, Cetara Anchovy Fillets, Black Olives and Garlic.', price: '16,00' },
    { name: 'Capricciosa', description: "Tomato, Basil, Mozzarella, Porchetta d'Ariccia, Mushrooms, Black Olives and Baked Artichokes.", price: '17,00' },
    { name: 'Diavola', description: "Tomato, Basil, Mozzarella and 'Nduja.", price: '15,50' },
    { name: 'Calabrese', description: 'Tomato, Basil, Smoked Scamorza Cheese, Spicy Salami, Tropea Red Onions and Black Olives.', price: '18,00' },
    { name: 'Boscaiola', description: 'Tomato, Basil, Smoked Scamorza Cheese, Mascarpone, Mushrooms, Rocket and Parmigiano Reggiano Cheese flakes.', price: '16,00' },
    { name: 'Bresaola e tartufo', description: "Tomato, Mozzarella, Rocket, Punta d'Anca Bresaola, Parmigiano Reggiano Cheese flakes and Black Truffle.", price: '20,00' },
    { name: 'Crudaiola', description: 'Tomato, Rocket, Culatello, Parmigiano Reggiano Cheese flakes, Burrata Cream, Datterini Tomatoes, Basil and Oregano.', price: '20,00' },
    { name: 'Vegana', description: 'Tomato, Mix of Vegetables, Rocket and Dried Tomatoes.', price: '15,00' },
    { name: 'Vegetariana', description: 'Tomato, Mozzarella and a Mix of Vegetables.', price: '16,00' },
    { name: 'Calzone', description: 'The "Pizzaiolo" will surprise you!.', price: '19,00' },
  ],
  whitePizzas: [
    { name: 'Salsiccia Friarelli', description: 'Fior di latte, Basil, Sausage and Friarielli.', price: '17,00' },
    { name: '4 Formaggi', description: 'Fior di latte, Smoked Scamorza cheese, Gorgonzola cheese, Parmigiano Reggiano Cheese and Basil.', price: '16,00' },
    { name: 'Fresca', description: 'Fior di latte, yellow and red Datterini Tomatoes, Rocket and Parmigiano Reggiano Cheese flakes.', price: '16,00' },
    { name: 'Patate & Tartufo', description: 'Fior di latte, Basil, boiled Potatoes and Black Truffle.', price: '20,00' },
    { name: 'Mortadella', description: 'Fior di latte, Rocket, Mortadella, Pecorino Romano cheese flakes, Dried Tomato Pesto and Toasted Pistachios.', price: '20,00' },
    { name: 'Genovese', description: 'Fior di latte, Genoese Pesto, yellow and red Tomatoes from Piennolo del Vesuvio, Ricotta cheese flakes and Toasted Pine Nuts.', price: '20,00' },
  ],
  specials: [
    { name: 'Amatrice', description: 'Red piennolo tomato, Tropea red onion, crispy guanciale, black pepper, basil.', price: '20,00' },
    { name: 'Porchetta & tartufo', description: 'Tomato, basil, fiordilatte, Ariccia porchetta, mascarpone, black truffle.', price: '20,00' },
    { name: 'Nostra', description: 'Tomato, Apulian burratina, culatello, black truffle and basil.', price: '20,00' },
    { name: 'Piccantissima', description: 'Tomato, basil, fiordilatte, spicy salami, nduja, 1/2 burrata in the center, chili threads.', price: '20,00' },
    { name: 'Napoli special', description: 'Tomato, basil, burrata, capers, Cetara anchovies.', price: '20,00' },
    { name: 'Burrata & pesto', description: 'Tomato, burrata, cherry tomatoes, homemade Genovese pesto, toasted pine nuts, parmesan flakes.', price: '20,00' },
    { name: 'Tricolore', description: 'Tomato, basil, burrata, spicy salami, homemade Genovese pesto, toasted pine nuts.', price: '20,00' },
    { name: 'Parmigiana', description: 'Tomato, buffalo mozzarella, eggplants, datterini tomatoes, parmesan flakes, oregano.', price: '20,00' },
  ],
  wines: winesEn,
  testimonials: [
    { id: 1, rating: 5, quote: "This Resteraunt is just amazing. The Staff is very friendly and polite. If you wanna eat an ORIGINAL italian Pizza and drink a real coffee, don't miss to go there. I will come again.", attribution: 'Okan35 B.' },
    { id: 2, rating: 4, quote: "Really good pizza and very nice people. We absolutely loved it and will certainly be back to enjoy an evening with a bottle of wine to go with our food. In the meantime we'll probably order again. Highly recommended.", attribution: 'Wim Dekkers' },
    { id: 3, rating: 5, quote: 'This is the right place of you want to enjoy a really good pizza ! You’ll find the traditional tastes and also some nice composition and good choice of wine too.', attribution: 'Lorenzo Vinc' },
  ],
  delivery: deliveryEn,
  footer: {
    description: "Click the icons to find us on a map or on social media. Want to book a table or order a pizza? Click the phone! We’re waiting for you!",
    deliveryTitle: 'Order online',
    socialTitle: 'Follow Pizza Vino',
    legalLine: 'Pizza Vino · Avenue des Saisons 15, 1050 Ixelles · VAT BE 0727796146',
  },
}
