import { categories, deliveryFr, galleriesFr, partners, winesFr } from '~/content/home/shared'
import type { HomeContent } from '~/content/home/types'

export const homeFr: HomeContent = {
  key: 'home-fr',
  locale: 'fr',
  path: '/',
  langLabel: 'Français',
  navigation: {
    menu: 'Les pizzas',
    wines: 'Les vins',
    visit: 'Nous trouver',
  },
  hero: {
    title: 'Pizza napolitaine, vins italiens et vraie convivialité à Ixelles',
    lead: 'Trois choses auxquelles vous ne pouvez absolument pas renoncer.',
    bullets: ['Une excellente pizza.', 'Un bon verre de vin.', 'Une adresse où l’on revient avec plaisir.'],
    pdfHref: '/doc/pizza-vino-fr.pdf',
    pdfLabel: 'Télécharger la carte',
    callLabel: 'Appeler',
    heroImage: '/img/header-def.jpg',
  },
  heroHighlight: {
    locationLabel: 'Ixelles, Brussels',
    title: 'Pizza napolitaine et cave italienne',
    description: 'Pizza Vino réunit la tradition italienne, une pâte légère à longue maturation et une sélection de vins pensée pour la table.',
    doughLabel: 'Pâte',
    doughValue: '48–72h de maturation',
    serviceLabel: 'Service',
    serviceValue: 'Sur place, emporter, livraison',
  },
  labels: {
    craftsmanshipTitle: 'Fabriqué avec amour',
    craftsmanshipSubtitle: 'Pâte légère, cuisson vive au four rotatif bois et gaz, ingrédients italiens soigneusement sélectionnés.',
    galleryTitle: 'Galerie',
    gallerySubtitle: 'Un aperçu de la pizza, du four, de l’équipe et de la salle chez Pizza Vino.',
    menuIntroTitle: 'Et maintenant, place à la carte',
    redPizzasTitle: 'Pizze rosse',
    redPizzasDescription: 'Une base tomate Piennolo au goût vif et équilibré, emblématique de la tradition napolitaine.',
    whitePizzasTitle: 'Pizze bianche',
    whitePizzasDescription: 'Des recettes pensées sans sauce tomate pour laisser toute la place aux produits italiens de caractère.',
    specialsTitle: 'Les suggestions les plus demandées',
    winesTitle: 'Sélection de vins',
    winesDescription: 'Une carte courte, italienne et cohérente avec les pizzas, pensée pour accompagner chaque bouchée.',
    testimonialsTitle: 'Votre avis est très important pour nous',
    testimonialsSubtitle: 'Vos commentaires sont notre meilleure publicité. Merci de partager votre expérience.',
    deliveryTitle: 'Livraison et commande',
    visitTitle: 'Venez chez Pizza Vino',
    addressTitle: 'Adresse',
    phoneTitle: 'Téléphone',
  },
  supportLinks: [
    {
      name: 'Four à bois Valoriani',
      description: 'Un four italien reconnu par les professionnels de la vraie pizza napolitaine pour sa cuisson rapide, régulière et fidèle aux saveurs d’origine.',
      imageSrc: '/img/forno.jpeg',
    },
    {
      name: 'Produits italiens choisis avec soin',
      description: 'Farines, tomates, fromages, charcuteries et légumes sont sélectionnés pour offrir une pizza digeste, généreuse et intensément savoureuse.',
      imageSrc: '/img/pizza-primo-piano3.webp',
    },
    {
      name: 'Le parcours de Michele',
      description: 'Michele a grandi entre tradition italienne, technique et passion. À Bruxelles, il défend une vision claire: une pizza honnête, précise et pleine de personnalité.',
      imageSrc: '/img/michele-one.jpeg',
    },
  ],
  categories,
  galleries: galleriesFr,
  redPizzas: [
    { name: 'Margherita', description: 'Tomate, basilic et mozzarella.', price: '11,00' },
    { name: 'Regina', description: 'Tomate, basilic et mozzarella de bufflonne.', price: '15,00' },
    { name: 'Principessa', description: 'Tomate, basilic et scamorza fumée.', price: '13,00' },
    { name: 'Burrata', description: "Tomate, basilic, tomates datterini et burratina d'Andria.", price: '18,00' },
    { name: 'Marinara', description: 'Tomate, ail, origan et basilic.', price: '10,00' },
    { name: 'Rucola Reggiano', description: 'Tomate, mozzarella, roquette et Parmigiano Reggiano.', price: '14,00' },
    { name: 'Porchetta Funghi', description: "Tomate, basilic, mozzarella, porchetta d'Ariccia et champignons.", price: '16,00' },
    { name: 'Quattro Stagioni', description: "Tomate, basilic, mozzarella, porchetta d'Ariccia, champignons, olives noires et artichauts au four.", price: '17,00' },
    { name: 'Napoli', description: 'Tomate, mozzarella, câpres, filets d’anchois de Cetara et origan.', price: '15,00' },
    { name: 'Siciliana', description: 'Tomate, basilic, mozzarella, câpres, anchois de Cetara, olives noires et ail.', price: '16,00' },
    { name: 'Diavola', description: 'Tomate, basilic, mozzarella et nduja.', price: '15,50' },
    { name: 'Bresaola e tartufo', description: 'Tomate, mozzarella, roquette, bresaola, copeaux de grana et truffe noire.', price: '20,00' },
  ],
  whitePizzas: [
    { name: 'Salsiccia Friarelli', description: 'Mozzarella, basilic, saucisse et friarielli.', price: '17,00' },
    { name: '4 Formaggi', description: 'Mozzarella, scamorza fumée, gorgonzola, parmesan et basilic.', price: '16,00' },
    { name: 'Fresca', description: 'Mozzarella, datterini jaunes et rouges, roquette et parmesan.', price: '16,00' },
    { name: 'Patate & Tartufo', description: 'Mozzarella, basilic, pommes de terre et truffe noire.', price: '20,00' },
    { name: 'Mortadella', description: 'Mozzarella, roquette, mortadelle, pecorino, pesto de tomates séchées et pistaches.', price: '20,00' },
    { name: 'Genovese', description: 'Mozzarella, pesto génois, tomates del Piennolo, ricotta et pignons grillés.', price: '20,00' },
  ],
  specials: [
    { name: 'Amatrice', description: 'Tomate piennolo rouge, oignon rouge de Tropea, guanciale croustillant, poivre noir et basilic.', price: '20,00' },
    { name: 'Porchetta & tartufo', description: "Tomate, basilic, fiordilatte, porchetta d'Ariccia, mascarpone et truffe noire.", price: '20,00' },
    { name: 'Nostra', description: 'Tomate, burratina des Pouilles, culatello, truffe noire et basilic.', price: '20,00' },
    { name: 'Piccantissima', description: 'Tomate, fiordilatte, salami piquant, nduja, demi-burrata et fils de piment.', price: '20,00' },
    { name: 'Burrata & pesto', description: 'Tomate, burrata, tomates cerises, pesto génois maison, pignons grillés et parmesan.', price: '20,00' },
    { name: 'Parmigiana', description: 'Tomate, mozzarella de bufflonne, aubergines, datterini, parmesan et origan.', price: '20,00' },
  ],
  wines: winesFr,
  testimonials: [
    {
      id: 1,
      rating: 5,
      quote: "Meilleure pizza ever. La pâte est incroyable, les ingrédients aussi, et l'équipe reste attentionnée même quand ça tourne fort.",
      attribution: 'Florian Durie',
    },
    {
      id: 2,
      rating: 5,
      quote: 'Depuis que j’ai goûté Pizza Vino, je ne veux plus manger de pizza ailleurs. La pâte est cuite à la perfection et les produits sont remarquables.',
      attribution: 'Warlikka',
    },
    {
      id: 3,
      rating: 5,
      quote: 'De vrais Italiens, un décor moderne, une pâte fine et des produits sérieux. Le rapport qualité-prix est excellent.',
      attribution: 'Gilles Marechal',
    },
  ],
  delivery: deliveryFr,
  footer: {
    description: 'Cliquez sur les icônes pour nous trouver sur la carte, réserver, commander ou nous suivre sur les réseaux sociaux.',
    deliveryTitle: 'Commander',
    socialTitle: 'Suivre Pizza Vino',
    legalLine: 'Pizza Vino · Avenue des Saisons 15, 1050 Ixelles · TVA BE 0727796146',
  },
}
