import { categories, deliveryFr, galleriesFr, winesFr } from '~/content/home/shared'
import type { HomeContent } from '~/content/home/types'

export const homeFr: HomeContent = {
  key: 'home-fr',
  locale: 'fr',
  path: '/',
  langLabel: 'Français',
  navigation: {
    menu: 'Les pizzas',
    wines: 'Les vins',
    visit: 'Contact',
  },
  hero: {
    title: 'Per chi ama la pizza',
    lead: 'Trois choses auxquelles vous ne pouvez absolument pas renoncer:',
    bullets: ['Une excellente pizza..', 'Un bon verre de vin.', '...'],
    pdfHref: '/doc/pizza-vino-fr.pdf',
    pdfLabel: 'Télécharger carte',
    callLabel: 'Appel',
    heroImage: '/img/header-def.jpg',
  },
  heroHighlight: {
    locationLabel: 'Ixelles, Brussels',
    title: 'Pizza napolitaine et cave italienne',
    description: 'Pizza Vino réunit la tradition italienne, une pâte légère à longue maturation et une sélection de vins pensée pour la table.',
    doughLabel: 'Pâte',
    doughValue: '48–72h de maturation',
    serviceLabel: 'Service',
    serviceValue: 'Sur place, emporter, livraison',
  },
  labels: {
    craftsmanshipTitle: 'Made with love',
    craftsmanshipSubtitle: 'Made with love',
    craftsmanshipBody: "Une pâte légère qui repose entre 48 et 72 heures avant d'être utilisée, réalisée avec des ingrédients de haute qualité, pour obtenir une corniche prononcée mais évidée; la cuisson dans un four rotatif combiné gaz / bois à 450°C permet de conserver les saveurs authentiques de la tomate et de la mozzarella fiordilatte.",
    galleryTitle: 'Gallery',
    gallerySubtitle: 'Gallery',
    menuIntroTitle: 'Mais maintenant place a ...',
    redPizzasTitle: 'Pizze Rosse',
    redPizzasDescription: 'Sauce à base de tomate Piennolo, typique de la région vésuvienne de Campanie, elle doit son nom à la manière dont les grappes sont entrelacées pour être conservées. Ils ont une forme ovale mais allongée et un goût typiquement acide.',
    whitePizzasTitle: 'Pizze bianche',
    whitePizzasDescription: 'Expressément conçu sans sauce tomate pour rehausser les saveurs typiques des produits italiens uniques. Une combinaison époustouflante qui ravira vos papilles.',
    specialsTitle: 'Les suggestions les plus demandées',
    winesTitle: 'Sélection de vins',
    winesDescription: "Ce qui compte c'est que cette fois pour accompagner ta pizza il y aura du bon vin.",
    testimonialsTitle: 'Votre avis est très important pour nous!',
    testimonialsSubtitle: 'Nous vous demandons de laisser un commentaire. Parce que vos commentaires sont notre meilleure publicité. Merci !',
    testimonialsListTitle: 'Que disent les gens ?',
    deliveryTitle: 'Livraison et commande',
    visitTitle: 'Venez chez Pizza Vino',
    addressTitle: 'Adresse',
    phoneTitle: 'Téléphone',
  },
  supportLinks: [
    {
      name: 'Four à bois',
      description: "Design absolument italien depuis plus d'un siècle, excellentes performances, les fours Valoriani sont internationalement reconnus. Certifications et certificats reçus de la Napolitan True Pizza Association, de partenaires tels que Slow Food, Gambero Rosso, Witaly etc...",
      imageSrc: '/img/forno.jpeg',
    },
    {
      name: 'Produits de qualité',
      description: "Pour nous, il est important de servir une pizza de haute qualité. Des produits de haute qualité à des prix abordables pour offrir aux clients un produit final excellent au goût et facile à digérer. Les ingrédients strictement d'origine italienne (et la façon dont ils sont traités) sont, surtout en ce qui concerne la pizza, la partie la plus importante.",
      imageSrc: '/img/pizza-primo-piano3.webp',
    },
    {
      name: 'Il Pizzaiolo',
      description: "Passionné de cuisine depuis l'âge de 14 ans, Michele décide pendant la period du lycée de commencer à travailler dans un restaurant-pizzeria dans la province de Vérone, où se trouvent ses racines. Il arrive à Bruxelles à 21 ans après un an d'expérience en Allemagne. En 2019 à 27 ans, il couronne le rêve d'ouvrir son propre restaurant où il est libre d'exprimer son meilleur concept de pizza.",
      imageSrc: '/img/michele-one.jpeg',
    },
  ],
  categories,
  galleries: galleriesFr,
  redPizzas: [
    { name: 'Margherita', description: 'Tomate, Basilic et Mozzarella.', price: '11,00' },
    { name: 'Regina', description: 'Tomate, Basilic et Mozzarella de Bufflonne.', price: '15,00' },
    { name: 'Principessa', description: 'Tomate, Basilic et Scamorza fumée.', price: '13,00' },
    { name: 'Burrata', description: "Tomate, Basilic, Tomates Datterini et Burratina d'Andria.", price: '18,00' },
    { name: 'Marinara', description: 'Tomate, Ail, Origan et Basilic.', price: '10,00' },
    { name: 'Rucola Reggiano', description: 'Tomate, Mozzarella, Roquette et Parmigiano Reggiano.', price: '14,00' },
    { name: 'Porchetta Funghi', description: "Tomate, Basilic, Mozzarella, Porchetta d'Ariccia et Champignons.", price: '16,00' },
    { name: 'Quattro Stagioni', description: "Tomate, Basilic, Mozzarella, Porchetta d'Ariccia, Champignons, Olives Noires et Artichauts au four.", price: '17,00' },
    { name: 'Napoli', description: "Tomate, Mozzarella, Câpres, Filets d'Anchois de Cetara et Origan.", price: '15,00' },
    { name: 'Siciliana', description: "Tomate, Basilic, Mozzarella, Câpres, Filets d'Anchois de Cetara, Olives Noires et Ail.", price: '16,00' },
    { name: 'Capricciosa', description: "Tomate, Basilic, Mozzarella, Porchetta d'Ariccia, Champignons, Olives Noires et Artichauts au four.", price: '17,00' },
    { name: 'Diavola', description: "Tomate, Basilic, Mozzarella et 'Nduja.", price: '15,50' },
    { name: 'Calabrese', description: 'Tomate, Basilic, Scamorza fumée, Salami épicé, Oignons rouges de Tropea et Olives Noires.', price: '18,00' },
    { name: 'Boscaiola', description: 'Tomate, Basilic, Scamorza fumée, Mascarpone, Champignons, Roquette et copeaux de Grana.', price: '16,00' },
    { name: 'Bresaola e tartufo', description: "Tomate, Mozzarella, Roquette, Bresaola de Punta d'Anca, copeaux de Grana et Truffe Noire.", price: '20,00' },
    { name: 'Crudaiola', description: 'Tomate, Roquette, Culatello, copeaux de Grana, Crème Burrata, Tomates Datterini, Basilic et Origan.', price: '20,00' },
    { name: 'Vegana', description: 'Tomate, Mélange de légumes, Roquette et Tomates séchées.', price: '15,00' },
    { name: 'Vegetariana', description: 'Tomate, Mozzarella et Mélange de légumes.', price: '16,00' },
    { name: 'Calzone', description: 'Surprise du pizzaiolo!', price: '19,00' },
  ],
  whitePizzas: [
    { name: 'Salsiccia Friarelli', description: 'Mozzarella, Basilic, Saucisse et Friarielli.', price: '17,00' },
    { name: '4 Formaggi', description: 'Mozzarella, Scamorza fumée, Gorgonzola, Copeaux de Parmesan et Basilic.', price: '16,00' },
    { name: 'Fresca', description: 'Mozzarella, Tomates datterini jaunes et rouges, Roquette et Copeaux de Parmesan.', price: '16,00' },
    { name: 'Patate & Tartufo', description: 'Mozzarella, Basilic, Pommes de terre bouillies et Truffe Noire.', price: '20,00' },
    { name: 'Mortadella', description: 'Mozzarella, Roquette, Mortadelle, Copeaux de Pecorino Romano, Pesto de tomates séchées et Pistaches grillées.', price: '20,00' },
    { name: 'Genovese', description: 'Mozzarella, Pesto Génois, Tomates jaunes et rouges de Piennolo del Vesuvio, Ricotta, Copeaux de Grana et Pignons de pin grillés.', price: '20,00' },
  ],
  specials: [
    { name: 'Amatrice', description: 'Tomate piennolo rouge, oignon rouge de Tropea, guanciale croustillant, poivre noir, basilic.', price: '20,00' },
    { name: 'Porchetta & tartufo', description: "Tomate, basilic, fiordilatte, porchetta d'Ariccia, mascarpone, truffe noire.", price: '20,00' },
    { name: 'Nostra', description: 'Tomate, burratina des Pouilles, culatello, truffe noire et basilic.', price: '20,00' },
    { name: 'Piccantissima', description: 'Tomate, basilic, fiordilatte, salami piquant, nduja, 1/2 burrata au centre, fils de piment.', price: '20,00' },
    { name: 'Napoli special', description: 'Tomate, basilic, burrata, câpres, anchois de Cetara.', price: '20,00' },
    { name: 'Burrata & pesto', description: 'Tomate, burrata, tomates cerises, pesto génois maison, pignons grillés, copeaux de parmesan.', price: '20,00' },
    { name: 'Tricolore', description: 'Tomate, basilic, burrata, salami piquant, pesto génois maison, pignons grillés.', price: '20,00' },
    { name: 'Parmigiana', description: 'Tomate, mozzarella de bufflonne, aubergines, datterini, copeaux de parmesan, origan.', price: '20,00' },
  ],
  wines: winesFr,
  testimonials: [
    { id: 1, rating: 5, quote: "Meilleure pizza ever. La pate est incroyable et les ingrédients aussi. La Boscaiola est une tuerie avec sa scamorza fumée. Je conseille vivement. Le personnel est super sympa et attentionné même quand il s'agit du rush et que l'on commande à emporter.", attribution: 'Florian Durie' },
    { id: 2, rating: 5, quote: "Honnêtement, depuis que j'ai goûté aux succulentes pizzas de Pizza Vino, je ne veux plus manger de pizza dans un autre restaurant. La pâte est délicieuse, cuite à la perfection et les ingrédients sont de qualité et bien mis en valeur.", attribution: 'Warlikka' },
    { id: 3, rating: 5, quote: "Des vrais italiens, un décor moderne. La pizza avec de la vraie farine italienne et du bon jambon fumé. La pate est fine. Le prix est raisonable vu la qualité des produits.", attribution: 'Gilles Marechal' },
  ],
  delivery: deliveryFr,
  footer: {
    description: 'Cliquez sur les icônes pour nous trouver sur une carte ou sur les réseaux sociaux. Vous souhaitez réserver une table ou commander une pizza ? Cliquez sur le téléphone ! Nous vous attendons !',
    deliveryTitle: 'Commander',
    socialTitle: 'Suivre Pizza Vino',
    legalLine: 'Pizza Vino · Avenue des Saisons 15, 1050 Ixelles · TVA BE 0727796146',
  },
}
