import { categories, deliveryIt, galleriesIt, partners, winesIt } from '~/content/home/shared'
import type { HomeContent } from '~/content/home/types'

export const homeIt: HomeContent = {
  key: 'home-it',
  locale: 'it',
  path: '/it',
  langLabel: 'Italiano',
  navigation: {
    menu: 'Le pizze',
    wines: 'I vini',
    visit: 'Vieni a trovarci',
  },
  hero: {
    title: 'Pizza napoletana autentica a Ixelles con vini italiani e ingredienti selezionati',
    lead: 'A tre cose non si può assolutamente rinunciare.',
    bullets: ['Un’ottima pizza.', 'Un buon bicchiere di vino.', 'Un luogo che sa farti tornare.'],
    pdfHref: '/doc/pizza-vino-it.pdf',
    pdfLabel: 'Scarica il menu',
    callLabel: 'Chiama',
    heroImage: '/img/new-header.jpg',
  },
  heroHighlight: {
    locationLabel: 'Ixelles, Brussels',
    title: 'Pizza napoletana e cave italiana',
    description: 'Pizza Vino unisce tradizione italiana, impasto leggero a lunga maturazione e una selezione di vini pensata per stare bene a tavola.',
    doughLabel: 'Impasto',
    doughValue: '48–72h maturazione',
    serviceLabel: 'Servizio',
    serviceValue: 'Sala, asporto, delivery',
  },
  labels: {
    craftsmanshipTitle: 'Fatta con amore',
    craftsmanshipSubtitle: 'Impasto leggero, lunga maturazione e cottura veloce per una pizza fragrante, scioglievole e riconoscibile.',
    galleryTitle: 'Gallery',
    gallerySubtitle: 'Uno sguardo alla pizza, al forno e alla sala di Pizza Vino.',
    menuIntroTitle: 'Adesso spazio al menu',
    redPizzasTitle: 'Pizze rosse',
    redPizzasDescription: 'Il pomodoro del Piennolo porta acidità, profumo e identità campana alla base delle nostre pizze rosse.',
    whitePizzasTitle: 'Pizze bianche',
    whitePizzasDescription: 'Ricette senza salsa di pomodoro, costruite per esaltare latticini, salumi, ortaggi e profumi italiani.',
    specialsTitle: 'Le suggestioni più richieste',
    winesTitle: 'Selezione di vini',
    winesDescription: 'Una carta pensata per accompagnare la pizza con equilibrio, freschezza e carattere.',
    testimonialsTitle: 'La tua opinione conta',
    testimonialsSubtitle: 'Le recensioni aiutano chi non ci conosce ancora a capire cosa trova davvero da Pizza Vino.',
    deliveryTitle: 'Ordina e ricevi',
    visitTitle: 'Vieni da Pizza Vino',
    addressTitle: 'Indirizzo',
    phoneTitle: 'Telefono',
  },
  supportLinks: [
    {
      name: 'Forno Valoriani',
      description: 'Un forno italiano riconosciuto dagli specialisti della pizza napoletana per precisione di cottura, spinta e profumo.',
      imageSrc: '/img/forno.jpeg',
    },
    {
      name: 'Materie prime di qualità',
      description: 'Farine, pomodori, latticini e salumi vengono scelti per dare alla pizza gusto pieno, digeribilità e identità italiana.',
      imageSrc: '/img/pizza-primo-piano3.webp',
    },
    {
      name: 'La mano di Michele',
      description: 'Esperienza, tecnica e sensibilità per il prodotto si ritrovano in una pizza precisa ma mai rigida, con carattere e personalità.',
      imageSrc: '/img/michele-one.jpeg',
    },
  ],
  categories,
  galleries: galleriesIt,
  redPizzas: [
    { name: 'Margherita', description: 'Pomodoro, basilico e fior di latte.', price: '11,00' },
    { name: 'Regina', description: 'Pomodoro, basilico e mozzarella di bufala.', price: '15,00' },
    { name: 'Principessa', description: 'Pomodoro, basilico e scamorza affumicata.', price: '13,00' },
    { name: 'Burrata', description: "Pomodoro, basilico, burratina d'Andria e datterini.", price: '18,00' },
    { name: 'Marinara', description: 'Pomodoro, aglio, origano e basilico.', price: '10,00' },
    { name: 'Rucola Reggiano', description: 'Pomodoro, fior di latte, rucola e Parmigiano Reggiano.', price: '14,00' },
    { name: 'Porchetta Funghi', description: "Pomodoro, basilico, fior di latte, porchetta d'Ariccia e funghi.", price: '16,00' },
    { name: 'Quattro Stagioni', description: "Pomodoro, basilico, fior di latte, porchetta d'Ariccia, funghi, olive nere e carciofi al forno.", price: '17,00' },
    { name: 'Napoli', description: 'Pomodoro, fior di latte, capperi, alici di Cetara e origano.', price: '15,00' },
    { name: 'Siciliana', description: 'Pomodoro, basilico, fior di latte, capperi, alici di Cetara, olive nere e aglio.', price: '16,00' },
    { name: 'Diavola', description: 'Pomodoro, basilico, fior di latte e nduja.', price: '15,50' },
    { name: 'Bresaola e tartufo', description: 'Pomodoro, fior di latte, rucola, bresaola, scaglie di grana e tartufo nero.', price: '20,00' },
  ],
  whitePizzas: [
    { name: 'Salsiccia Friarelli', description: 'Fior di latte, basilico, salsiccia e friarielli.', price: '17,00' },
    { name: '4 Formaggi', description: 'Fior di latte, scamorza affumicata, gorgonzola, grana e basilico.', price: '16,00' },
    { name: 'Fresca', description: 'Fior di latte, datterini gialli e rossi, rucola e scaglie di grana.', price: '16,00' },
    { name: 'Patate & Tartufo', description: 'Fior di latte, basilico, patate e tartufo nero.', price: '20,00' },
    { name: 'Mortadella', description: 'Fior di latte, rucola, mortadella, pecorino, pesto di pomodori secchi e pistacchi.', price: '20,00' },
    { name: 'Genovese', description: 'Fior di latte, pesto genovese, pomodorini del Piennolo, ricotta e pinoli tostati.', price: '20,00' },
  ],
  specials: [
    { name: 'Amatrice', description: 'Pomodoro piennolo rosso, cipolla di Tropea, guanciale croccante, pepe nero e basilico.', price: '20,00' },
    { name: 'Porchetta & tartufo', description: "Pomodoro, basilico, fiordilatte, porchetta d'Ariccia, mascarpone e tartufo nero.", price: '20,00' },
    { name: 'Nostra', description: 'Pomodoro, burratina pugliese, culatello, tartufo nero e basilico.', price: '20,00' },
    { name: 'Piccantissima', description: "Pomodoro, fiordilatte, salamino piccante, nduja, mezza burrata e fili di peperoncino.", price: '20,00' },
    { name: 'Burrata & pesto', description: 'Pomodoro, burrata, pomodorini, pesto genovese home made, pinoli tostati e scaglie di grana.', price: '20,00' },
    { name: 'Parmigiana', description: 'Pomodoro, mozzarella di bufala, melanzane, datterini, scaglie di grana e origano.', price: '20,00' },
  ],
  wines: winesIt,
  testimonials: [
    {
      id: 1,
      rating: 5,
      quote: 'Tra le migliori pizze mangiate a Bruxelles: prodotti di qualità, locale accogliente e personale davvero simpatico.',
      attribution: 'Yuri Abbate',
    },
    {
      id: 2,
      rating: 5,
      quote: 'Ristorante tipico italiano, bellissimo. Pizze con prodotti freschi e servizio impeccabile. Da rifare.',
      attribution: 'Mauran Art',
    },
    {
      id: 3,
      rating: 5,
      quote: 'Atmosfera rilassata, servizio caloroso e pizze varie e davvero deliziose. Si sente la qualità sia nell’impasto sia nella guarnitura.',
      attribution: 'Fab Verdi',
    },
  ],
  delivery: deliveryIt,
  footer: {
    description: 'Usa i link qui sotto per trovarci sulla mappa, ordinare una pizza o seguire Pizza Vino sui social.',
    deliveryTitle: 'Ordina online',
    socialTitle: 'Segui Pizza Vino',
    legalLine: 'Pizza Vino · Avenue des Saisons 15, 1050 Ixelles · TVA BE 0727796146',
  },
}
