import { categories, deliveryIt, galleriesIt, winesIt } from '~/content/home/shared'
import type { HomeContent } from '~/content/home/types'

export const homeIt: HomeContent = {
  key: 'home-it',
  locale: 'it',
  path: '/it',
  langLabel: 'Italiano',
  navigation: {
    menu: 'Le pizze',
    wines: 'I vini',
    visit: 'Contact',
  },
  hero: {
    title: 'Per chi ama la pizza',
    lead: 'A tre cose non si può assolutamente rinunciare:',
    bullets: ['Un ottima pizza.', 'Un buon bicchiere di vino.', '...'],
    pdfHref: '/doc/pizza-vino-it.pdf',
    pdfLabel: 'Scarica menù',
    callLabel: 'Chiama',
    heroImage: '/img/new-header.jpg',
  },
  heroHighlight: {
    locationLabel: 'Ixelles, Brussels',
    title: 'Pizza napoletana e cave italiana',
    description: 'Pizza Vino unisce tradizione italiana, impasto leggero a lunga maturazione e una selezione di vini pensata per stare bene a tavola.',
    doughLabel: 'Impasto',
    doughValue: '48–72h maturazione',
    serviceLabel: 'Servizio',
    serviceValue: 'Sala, asporto, delivery',
  },
  labels: {
    craftsmanshipTitle: 'Fatta con amore',
    craftsmanshipSubtitle: 'Fatta con amore',
    craftsmanshipBody: "Un impasto leggero che riposa tra le 48 e le 72 ore prima di essere utizzato, realizzato con ingredienti di alta qualità, per ottenere un cornicione pronunciato ma scavato all'interno; la cottura in un forno rotante misto gas / legna a 450°C permette di preservare i sapori autentici del pomodoro e della mozzarella fiordilatte.",
    galleryTitle: 'Gallery',
    gallerySubtitle: 'Gallery',
    menuIntroTitle: 'Ma adesso spazio alle ...',
    redPizzasTitle: 'Pizze Rosse',
    redPizzasDescription: "Sugo a base di pomodoro del Piennolo, tipico dell'area vesuviana campana, deve il suo nome al modo in cui i grappoli vengono intrecciati per essere conservati. Hanno una forma ovale ma allungata e un sapore tipicamente acidulo.",
    whitePizzasTitle: 'Pizze bianche',
    whitePizzasDescription: 'Espressamente pensate senza salsa di pomodoro per esaltare i sapori tipici di prodotti italiani unici. Una combinazione strabiliante che solleticherà le vostre papille gustative.',
    specialsTitle: 'Le suggestioni più richieste',
    winesTitle: 'Selezione di vini',
    winesDescription: 'Quello che conta è che questa volta ci sarà un buon vino ad accompagnarla.',
    testimonialsTitle: 'La tua opinione conta!',
    testimonialsSubtitle: 'Ti chiediamo di lasciare un commento. Perché i tuoi commenti sono la nostra migliore pubblicità. Grazie!',
    testimonialsListTitle: 'Casa dicono su di noi ?',
    deliveryTitle: 'Ordina e ricevi',
    visitTitle: 'Vieni da Pizza Vino',
    addressTitle: 'Indirizzo',
    phoneTitle: 'Telefono',
  },
  supportLinks: [
    {
      name: 'Forno a legna',
      description: "Design assolutamente italiano da più di un secolo, ottime prestazioni, i forni Valoriani sono riconosciuti a livello internazionale. Certificazioni e attestati ricevuti dall'Associazione Napoletana Vera Pizza, da partner come Slow Food, Gambero Rosso, Witaly ecc...",
      imageSrc: '/img/forno.jpeg',
    },
    {
      name: 'Qualità dei prodotti',
      description: 'Per noi è importante servire una pizza di alta qualità. Prodotti di alta qualità a prezzi convenienti per dare ai clienti un prodotto finale ottimo da gustare. Gli ingredienti rigorosamente italiani (e il modo in cui vengono lavorati) sono, soprattutto per quanto riguarda la pizza, la parte più importante.',
      imageSrc: '/img/pizza-primo-piano3.webp',
    },
    {
      name: 'Il Pizzaiolo',
      description: "Appassionato di cucina già dall'età di 14 anni, Michele decide durante il periodo del liceo di iniziare a lavorare in un ristorante-pizzeria nella provincia di Verona, dove affondano le sue radici. Arriva a Bruxelles all'età di 21 anni dopo un anno di esperienza in Germania, e nel 2019, a 27 anni, corona il sogno di aprire il suo proprio ristorante dove finalmente è libero di esprimere il suo miglior concetto di pizza.",
      imageSrc: '/img/michele-one.jpeg',
    },
  ],
  categories,
  galleries: galleriesIt,
  redPizzas: [
    { name: 'Margherita', description: 'Pomodoro, basilico e fior di latte.', price: '11,00' },
    { name: 'Regina', description: 'Pomodoro, basilico e mozzarella di bufala.', price: '15,00' },
    { name: 'Principessa', description: 'Pomodoro, basilico e scamorza affumicata.', price: '13,00' },
    { name: 'Burrata', description: "Pomodoro, basilico, burratina d'Andria e datterini.", price: '18,00' },
    { name: 'Marinara', description: 'Pomodoro, aglio, origano e basilico.', price: '10,00' },
    { name: 'Rucola Reggiano', description: 'Pomodoro, fior di latte, rucola e Parmigiano Reggiano.', price: '14,00' },
    { name: 'Porchetta Funghi', description: "Pomodoro, basilico, fior di latte, porchetta d'Ariccia e funghi.", price: '16,00' },
    { name: 'Quattro Stagioni', description: "Pomodoro, basilico, fior di latte, porchetta d'Ariccia, funghi, olive nere e carciofi al forno.", price: '17,00' },
    { name: 'Napoli', description: 'Pomodoro, fior di latte, capperi, filetti di alici di Cetara e origano.', price: '15,00' },
    { name: 'Siciliana', description: 'Pomodoro, basilico, fior di latte, capperi, filetti di alici di Cetara, olive nere e aglio.', price: '16,00' },
    { name: 'Capricciosa', description: "Pomodoro, basilico, fior di latte, porchetta d'Ariccia, funghi, olive nere e carciofi al forno.", price: '17,00' },
    { name: 'Diavola', description: "Pomodoro, basilico, fior di latte e 'Nduja", price: '15,50' },
    { name: 'Calabrese', description: 'Pomodoro, basilico, scamorza affumicata, salamino piccante, cipolle rosse di Tropea e olive nere.', price: '18,00' },
    { name: 'Boscaiola', description: 'Pomodoro, basilico, scamorza affumicata, mascarpone, funghi, rucola e scaglie di grana.', price: '16,00' },
    { name: 'Bresaola e tartufo', description: "Pomodoro, fior di latte, rucola, bresaola Punta d'Anca, scaglie di grana e tartufo nero.", price: '20,00' },
    { name: 'Crudaiola', description: 'Pomodoro, rucola, culatello, scaglie di grana, crema di burrata, datterini, basilico ed origano.', price: '20,00' },
    { name: 'Vegana', description: 'Pomodoro, mix di verdure, rucola e pomodori secchi.', price: '15,00' },
    { name: 'Vegetariana', description: 'Pomodoro, fior di latte e mix di verdure.', price: '16,00' },
    { name: 'Calzone', description: 'Sorpresa del pizzaiolo!.', price: '19,00' },
  ],
  whitePizzas: [
    { name: 'Salsiccia Friarelli', description: 'Fior di latte, basilico, salsiccia e friarielli Napoletani.', price: '17,00' },
    { name: '4 Formaggi', description: 'Fior di latte, scamorza affumicata, gorgonzola, scaglie di grana e basilico.', price: '16,00' },
    { name: 'Fresca', description: 'Fior di latte, datterini gialli e rossi, rucola e scaglie di grana.', price: '16,00' },
    { name: 'Patate & Tartufo', description: 'Fior di latte, basilico, patate lesse e tartufo nero.', price: '20,00' },
    { name: 'Mortadella', description: 'Fior di latte, rucola, mortadella, scaglie di pecorino Romano, pesto di pomodori secchi e pistacchi tostati.', price: '20,00' },
    { name: 'Genovese', description: 'Fior di latte, pesto alla genovese, pomodorini gialli e rossi del Piennolo del Vesuvio, ricotta, scaglie di grana e pinoli tostati.', price: '20,00' },
  ],
  specials: [
    { name: 'Amatrice', description: 'Pomodoro rosso piennolo, cipolla rossa di Tropea, guanciale croccante, pepe nero, basilico.', price: '20,00' },
    { name: 'Porchetta & tartufo', description: "Pomodoro, basilico, fiordilatte, porchetta d'Ariccia, mascarpone, tartufo nero.", price: '20,00' },
    { name: 'Nostra', description: 'Pomodoro, burratina pugliese, culatello, tartufo nero e basilico.', price: '20,00' },
    { name: 'Piccantissima', description: "Pomodoro, basilico, fiordilatte, salamino piccante, 'nduja, 1/2 burrata al centro, fili di peperoncino.", price: '20,00' },
    { name: 'Napoli special', description: 'Pomodoro, basilico, burrata, capperi, alici di Cetara.', price: '20,00' },
    { name: 'Burrata & pesto', description: 'Pomodoro, burrata, pomodorini, pesto genovese home made, pinoli tostati, scaglie di grana.', price: '20,00' },
    { name: 'Tricolore', description: 'Pomodoro, basilico, burrata, salamino piccante, pesto genovese home made, pinoli tostati.', price: '20,00' },
    { name: 'Parmigiana', description: 'Pomodoro, mozzarella di bufala, melanzane, datterini, scaglie di grana, origano.', price: '20,00' },
  ],
  wines: winesIt,
  testimonials: [
    { id: 1, rating: 5, quote: 'Un’esperienza unica davvero, ho provato tante pizzeria di Bruxelles ma questa non ha niente a vedere con le altre. Tutto in bella vista, prodotti di alta qualità, esteticamente ti fa sentire a casa il locale e il personale molto simpatico..', attribution: 'Yuri Abbate' },
    { id: 2, rating: 4, quote: 'Ristorante tipico italiano, bellissimo ! Erano le migliori pizze che abbiamo mangiato nella nostra vita, con prodotti freschi ! Il servizio è stato perfetto, il cameriere era così gentile, carino! Possibile mangiare vegan ! Ancora grazie di tutto ! Era davvero delizioso ! Ci vediamo presto.', attribution: 'Mauran Art' },
    { id: 3, rating: 5, quote: "Atmosfera veramente rilassante, con un servizio accogliente e caloroso ed ovviamente delle pizze variate e veramente deliziose. Consiglio a tutti di provare questa pizzeria, hanno dei prodotti freschi e di qualità che si risentono sia nella guarnitura della pizza che nell'impasto. Grazie ancora!.", attribution: 'Fab Verdi' },
  ],
  delivery: deliveryIt,
  footer: {
    description: 'Clicca sulle icone per trovarci sulla mappa o sui social. Vuoi prenotare un tavolo o ordinare una pizza? Clicca sul telefono! Ti stiamo aspettando!',
    deliveryTitle: 'Ordina online',
    socialTitle: 'Segui Pizza Vino',
    legalLine: 'Pizza Vino · Avenue des Saisons 15, 1050 Ixelles · TVA BE 0727796146',
  },
}
